openapi: 3.0.1
info:
  title: 'Data-Mapper Private API'
  version: '1.0.0'
  description: 'Микросервис "справочников" в рамках SecretCompanyNameID
  <br>
  <br>В качествое кода ошибки выводится название микросервиса с конкатенацией кода ошибки через двоеточие.
  <br><br>Пример: `DATA-MAPPER:001`<br><br>
  <b>Список кодов ошибок</b> `error_code` <b>возникающих Exceptions:</b>
  <br><br>`000` - Unprocessable error.
  <br><br>`001` - Too many requests in time moment.
  <br><br>`002` - Invalid or expired token.
  <br><br>`003` - Access denied.
  <br><br>`004` - The table must have a parent node.
  <br><br>`005` - Wrong parent link type.
  <br><br>`006` - Forbidden access.
  <br>
  <br>
  Flow для работы с методами API:
  <br>
  <br>
  Для просмотра справочника необходимо вызывать метод `/api/v1/private/directory/entity/all`. Данный метод позволит
  отрисовать связь родительских с дочерними узлами (таблицы так же могут наследоваться от других таблиц через внешние
  ключи)<br>
  После создания новой сущности (`entity`) - можно начинать наполнять новый справочник (в том случае, если это таблица).
  Для отрисовки формы наполнения созданной сущности необходимо вызывать метод `/api/v1/private/directory/column/all`
  с помощью которого можно получить структуру созданного справочника.
  <br>
  <br>
  В работе сервиса имеются ограничения. Они ограничения необходимы для избежания возникновения не обработанных
  исключений и не предвиденных ситуаций. По мере развития проекта данный список будет сокращаться путем исправлений
  на бэке.
  <br>
  <br>
  `Список ограничений, которые стоит соблюдать:`<br>
  - нельзя добавить таблицу без привязки родителя (таблицы или схемы), первым узлом всегда должна быть схема<br>
  - при добавления поля с relation_id (указателем) необходимо соблюдать единую общую типизацию (тип наследуемого
    связующего поля должен совпадать с родительским)<br>
  - поле с именем id создать нельзя<br>
  - нельзя пристраивать «руками» связь (relation) с родительской (связанной таблице), данная связь формируется
    автоматически<br>
  - запрещены связи между схемами (справочниками)<br>
  - стоит обратить внимание на то, что при удалении родительского узла (по parent_id) - удаляются все дочерние узлы<br>
  <br>
  '

paths: 'paths/_paths.yaml'
